title: Navpreet Singh
url: "https://realnav1234.github.io"
baseurl: "/personal-site/"

markdown: kramdown
ins_logo: "/personal-site/mit_logo.png"

remote_theme: ankitsultana/researcher@gem

plugins:
- jekyll-remote-theme

tracking_id: #

footer: no
# footer_url: "https://github.com/realnav1234"
# footer_text: "Page design by Ankit Sultana"

# twitter_username: "bluh"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "about"
   link: "/personal-site/"
 - name: "resume"
   link: "resume.pdf"
 - name: "contact"
   link: "contact"
 
