title: Navpreet Singh
url: "https://ankitsultana.com"
baseurl: "/personal-site/"

markdown: kramdown
ins_logo: "./mit_logo.png"

remote_theme: ankitsultana/researcher@gem

plugins:
- jekyll-remote-theme

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/personal-site/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
